import { SinkType, SourceType } from "../taint";

/* ================= SOURCES ================= */

// Attacker-controlled input
export const ATTACKER_SOURCES: SourceType[] = [
  "CHROME_SENDMESSAGE_EXTERNAL_RESPONSE",
  "CHROME_SENDNATIVEMESSAGE_EXTERNAL_RESPONSE",

  "CHROME_CONNECT_ONMESSAGE_EXTERANL",
  "CHROME_ONMESSAGEEXTERNAL_MESSAGE",
  "CHROME_ONCONNECTEXTERNAL_ONMESSAGE",
  "CHROME_CONNECTNATIVE_ONMESSAGE",

  "WINDOW_MESSAGE_EVENT",
  "WINDOW_CUSTOM_EVENT",
  "TARGET_CUSTOM_EVENT",
];

// Web event sources (used to filter DOM_XSS FP)
export const WEB_EVENT_SOURCES: SourceType[] = [
  "WINDOW_MESSAGE_EVENT",
  "WINDOW_CUSTOM_EVENT",
  "TARGET_CUSTOM_EVENT",
];


// Sensitive browser data
export const SENSITIVE_SOURCES: SourceType[] = [
  "CHROME_TABS_DETECT_LANUAGE",
  "CHROME_TABS_CAPUTURE_VISIBLE_TAB",
  "CHROME_BOOKMARK_INFO",
  "CHROME_COOKIES_INFO",
  "CHROME_COOKIES_STORE",
  "CHROME_HISTORY_INFO",
  "CHROME_READINGLIST_INFO",
  "CHROME_MANAGEMENT_INFO",
  "CHROME_DOWNLOADS_SEARCH",
  "CHROME_DOWNLOADS_FILEICON",

  "CHROME_TOPSITES_INFO",
  "CHROME_PAGECAPTURE_MHTML",
  "CHROME_IDENTITY_TOKEN",
  "CHROME_IDENTITY_PROFILE",

  "CHROME_BOOKMARKS_ONCREATED",
  "CHROME_COOKIES_ONCHANGED",
  "CHROME_DOWNLOADS_ONCHANGED",
  "CHROME_DOWNLOADS_ONCREATED",
  "CHROME_HISTORY_ONVISITED",
  "CHROME_MANAGEMENT_ONENABLED",
  "CHROME_MANAGEMENT_ONDISABLED",
  "CHROME_MANAGEMENT_ONINSTALLED",
];

// Fingerprint / system info
export const SYSTEM_SOURCES: SourceType[] = [
  "NAVIGAROR_GEOLOCATION",
  "NAVIGATOR_CLIPBOARD",
  "NAVIGATOR_CONNECTION",
  "NAVIGATOR_DEVICE_MEMORY",
  "NAVIGATOR_HARDWARE_CONCURRENCY",
  "NAVIGATOR_LANGUAGE",
  "NAVIGATOR_MAX_TOUCH_POINTS",
  "NAVIGATOR_PLATFORM",
  "NAVIGATOR_PLUGINS",
  "NAVIGATOR_USER_AGENT",
  "NAVIGATOR_GPU_ADAPTER",

  "SCREEN_INFO",

  "CHROME_FONTSETTINGS_FONTLIST",
  "CHROME_SYSTEM_CPU",
  "CHROME_SYSTEM_DISPLAY_LAYOUT",
  "CHROME_SYSTEM_DISPLAY",
  "CHROME_SYSTEM_MEMORY",
  "CHROME_SYSTEM_STORAGE",
];

// Network responses
export const NETWORK_SOURCES: SourceType[] = [
  "JQUERY_AJAX_RESPONSE",
  "FETCH_RESPONSE",
  "XML_HTTP_RESPONSE",
  "AXIOS_RESPONSE",
  "AXIOS_GET_RESPONSE",
  "AXIOS_POST_RESPONSE",
  "AXIOS_REQUEST_RESPONSE",
];

// DOM / document content
export const DOCUMENT_SOURCES: SourceType[] = [
  "ELEMENT_TEXT_CONTENT",
  "ELEMENT_INNER_HTML",
  "ELEMENT_OUTER_HTML",
  "ELEMENT_VALUE",
  "JQUERY_ELEMENT_VAL",
  "JQUERY_ELEMENT_TEXT",
  "JQUERY_ELEMENT_HTML",

  "DOCUMENT_COOKIE",
  "DOCUMENT_URL",
  "DOCUMENT_TITLE",
];

// Storage read
export const STORAGE_SOURCES: SourceType[] = [
  "STORAGE_ALL_ITEMS",
];

/* ================= SINKS ================= */

// Code execution
export const CODE_SINKS: SinkType[] = [
  "NEW_FUNCTION",
  "EVAL",
  "TIME_EVAL",
  "JQUERY_GLOBAL_EVAL",
  // Vue.compile turns a string into a render function — runtime codegen.
  "VUE_COMPILE",
];

// Network send
export const NETWORK_SINKS: SinkType[] = [
  "FETCH_RESOURCE",
  "FETCH_OPTIONS",
  "JQUERY_AJAX_URL",
  "JQUERY_AJAX_DATA",
  "JQUERY_AJAX_SETTINGS_URL",
  "JQUERY_AJAX_SETTINGS_DATA",
  "JQUERY_GET_URL",
  "JQUERY_GET_DATA",
  "JQUERY_POST_URL",
  "JQUERY_POST_DATA",
  "JQUERY_SETTINGS_URL",
  "JQUERY_SETTINGS_DATA",
  "XML_HTTP_REQUEST_OPEN",
  "XML_HTTP_REQUEST_SEND",
  "AXIOS_URL",
  "AXIOS_DATA",
  "AXIOS_HEADERS",
  "WEBSOCKET_URL",
  "WEBSOCKET_DATA",
];

// Message send
export const MESSAGE_SINKS: SinkType[] = [
  "CHROME_RUNTIME_SENDMESSAGE_EXTERNAL",
  "CHROME_RUNTIME_CONNECT_POSTMESSAGE_EXTERNAL",
  "CHROME_RUNTIME_ONMESSAGEEXTERNAL_SENDRESPONSE",
  "CHROME_RUNTIME_ONCONNECTEXTERNAL_POSTMESSAGE",
  "CHROME_RUNTIME_SENDNATIVEMESSAGE_EXTERNAL",
  "CHROME_RUNTIME_ONCONNECTNATIVE_POSTMESSAGE",

  "WINDOW_POSTMESSAGE",
];

// DOM write
export const DOM_SINKS: SinkType[] = [
  "JQUERY_ELEMENT_VAL_SET",
  "JQUERY_ELEMENT_TEXT_SET",
  "JQUERY_ELEMENT_HTML_SET",
  "DOCUMENT_WRITE",
  "DOCUMENT_EXECCOMMAND",
  // Generic + framework HTML-injection sinks.
  "DOM_INNER_HTML",
  "REACT_DANGEROUS_HTML",
  "VUE_V_HTML",
  "ANGULAR_BYPASS_SECURITY",
];

// Storage write
export const STORAGE_SINKS: SinkType[] = [
  // "WEB_LOCAL_STORAGE_SET_KEY",
  // "WEB_LOCAL_STORAGE_SET_VALUE",
  // "WEB_SESSION_STORAGE_SET_KEY",
  // "WEB_SESSION_STORAGE_SET_VALUE",
  "CHROME_LOCAL_STORAGE",
  "CHROME_SYNC_STORAGE",
  "CHROME_SESSION_STORAGE",
];


export const WEB_STORAGE_SINKS: SinkType[] = [
  "WEB_LOCAL_STORAGE_SET_KEY",
  "WEB_LOCAL_STORAGE_SET_VALUE",
  "WEB_SESSION_STORAGE_SET_KEY",
  "WEB_SESSION_STORAGE_SET_VALUE",
]

// Privileged APIs
export const PRIVILEGED_SINKS: SinkType[] = [
  "WEB_LOCAL_STORAGE_REMOVE",
  "WEB_SESSION_STORAGE_REMOVE",
  "CHROME_ACTION_DISABLE_TABID",
  "CHROME_ACTION_ENABLE_TABID",
  "CHROME_ACTION_BADGE_OPTIONS",
  "CHROME_ACTION_ICON_OPTIONS",
  "CHROME_ACTION_POPUP_OPTIONS",
  "CHROME_ACTION_TITLE_OPTIONS",
  "CHROME_ALARMS_CREATE_OPTIONS",
  "CHROME_ALARMS_CLEAR_NAME",
  "CHROME_BOOKMARK_CREATE_INFO",
  "CHROME_BOOKMARK_MOVE_ID",
  "CHROME_BOOKMARK_MOVE_DESTINATION",
  "CHROME_BOOKMARK_REMOVE_ID",
  "CHROME_BOOKMARK_REMOVE_TREE_ID",
  "CHROME_BOOKMARK_UPDATE_ID",
  "CHROME_BOOKMARK_UPDATE_INFO",
  "CHROME_BROWSINGDATA_REMOVE",
  "CHROME_COOKIES_SET_OPTIONS",
  "CHROME_COOKIES_REMOVE_OPTIONS",
  "CHROME_CONTENTSETTINGS_SET",
  "CHROME_CONTENTSETTINGS_CLEAR",
  "CHROME_DECLARATIVECONTENT_RULES",
  "CHROME_DECLARATIVECONTENT_RULE_IDS",
  "CHROME_DOWNLOADS_REMOVE_ID",
  "CHROME_DOWNLOADS_OPTIONS",
  "CHROME_FONTSETTINGS_SET_OPTIONS",
  "CHROME_FONTSETTINGS_SIZE_OPTIONS",
  "CHROME_GCM_SEND",
  "CHROME_HISTORY_ADD_URL",
  "CHROME_HISTORY_DELETE_RANGE",
  "CHROME_HISTORY_DELETE_URL",
  "CHROME_MANAGEMENT_SETENABLED_ID",
  "CHROME_MANAGEMENT_SETENABLED_FLAG",
  "CHROME_MANAGEMENT_UNINSTALL_ID",
  "CHROME_MANAGEMENT_LAUNCHAPP_ID",
  "CHROME_NOTIFICATIONS_CREATE_OPTIONS",
  "CHROME_NOTIFICATIONS_UPDATE_ID",
  "CHROME_NOTIFICATIONS_UPDATE_OPTIONS",
  "CHROME_NOTIFICATIONS_CLEAR_ID",
  "CHROME_PROXY_SETTINGS_SET",
  "CHROME_READINGLIST_ADD_OPTIONS",
  "CHROME_READINGLIST_REMOVE_URL",
  "CHROME_READINGLIST_UPDATE_OPTIONS",
  "CHROME_WINDOWS_UPDATE_OPTIONS",
  "CHROME_WINDOWS_CREATE_OPTIONS",

  "CHROME_TABS_CREATE_OPTIONS",
  "CHROME_TABS_EXECUTE",
];