import walkes, { RecurseFunction } from "../../ast/walkes";
import { FlowNode } from "../../flownode/flownode";
import { taintManager } from "../../taint";
import { defFactory } from "../factories/defFactory";
import Def from "../types/def";
import { setReachingDef } from "../utils/utils";
import { classTypeHandler } from "./classTypeHandler";
import { expressionTypeHandler } from "./expressionTypeHandler";
import { patternAwareTypeHandler } from "./patternAwareTypeHandler";

/**
 * Compute GEN set from AST nodes.
 *
 * This pass evaluates definitions generated by assignments,
 * declarations, class definitions, and loop iterations.
 */
export function computeGenFromAST(cfgNode: FlowNode) {
  if (!cfgNode.astNode) return;
  
  const scope = cfgNode.scope!;

  const visitor = {
    Program: (n: any, recurse: RecurseFunction) => {
      for (let stmt of n.body) recurse(stmt);
    },
    AssignmentExpression: (n: any, recurse: RecurseFunction) => {
      const rhsType = expressionTypeHandler(cfgNode, n.right);
      patternAwareTypeHandler(cfgNode, n.left, rhsType);
      
      // Ensure nested assignments inside RHS are processed
      recurse(n.right);
    },
    VariableDeclaration: (n: any, recurse: RecurseFunction) => {
      for (const decl of n.declarations) {
        recurse(decl);
      }
    },
    VariableDeclarator: (n: any, recurse: RecurseFunction) => {
      if (!n.id) return;

      if (n.init) {
        // Iterate through `init` to ensure that the internal assignments generate `GEN` first.
        recurse(n.init);
        const initType = expressionTypeHandler(cfgNode, n.init);
        patternAwareTypeHandler(cfgNode, n.id, initType);
      }
    },
    ClassDeclaration: (n: any, recurse: RecurseFunction) => {
      const className = n.id.name;
      // NOTE: Because class node has own scope but it declared at its parent scope
      const classVar = scope.parent?.getVariable(className);
      if (!classVar) return;
      const classDef = classTypeHandler(cfgNode, n, recurse);
      setReachingDef(classVar, classDef);
    },
    ForInStatement: (n: any) => {
      const rightType = expressionTypeHandler(cfgNode, n.right);
      handleForLoopLeft(cfgNode, n.left, rightType, false);
    },
    ForOfStatement: (n: any) => {
      const rightType = expressionTypeHandler(cfgNode, n.right);
      handleForLoopLeft(cfgNode, n.left, rightType, true);
    },
    ExportNamedDeclaration: (n: any, recurse: RecurseFunction) => {
      // export const a = ...
      // export function f() {}
      // export class C {}
      if (n.declaration) {
        recurse(n.declaration);
      }
      // export { a } / export { a } from 'm', specifiers NEVER generate GEN
    },
    ExportDefaultDeclaration: (n: any, recurse: RecurseFunction) => {
      const decl = n.declaration;

      // export default function f() {} / class C {}
      if (
        (decl.type === "FunctionDeclaration" ||
          decl.type === "ClassDeclaration") &&
        decl.id
      ) {
        recurse(decl);
        return;
      }

      // export default expr;
      // no GEN, but expression may have side-effects
      expressionTypeHandler(cfgNode, decl);
    },
    ExportAllDeclaration: () => {},
    CatchClause: () => {},
    /**
     * Handle expressions that may contain nested assignments
     * such as:
     *   const s = (c = E.url) != null ? c : "";
     */
    ConditionalExpression: (n: any, recurse: RecurseFunction) => {
      recurse(n.test);
      recurse(n.consequent);
      recurse(n.alternate);
    },
    BinaryExpression: (n: any, recurse: RecurseFunction) => {
      recurse(n.left);
      recurse(n.right);
    },
    SequenceExpression: (n: any, recurse: RecurseFunction) => {
      for (const e of n.expressions) recurse(e);
    },
    LogicalExpression: (n: any, recurse: RecurseFunction) => {
      recurse(n.left);
      recurse(n.right);
    },
    UnaryExpression: (n: any, recurse: RecurseFunction) => {
      recurse(n.argument);
    },
    ReturnStatement: (n: any, recurse: RecurseFunction) => {
      if (n.argument) recurse(n.argument);
    },
    default: () => {},
  };

  walkes(cfgNode.astNode, visitor);
}



/**
 * Helper: Extract the iterated content of a collection for for-in / for-of loops.
 *
 * for-of  → iterate over collection values
 * for-in  → iterate over property keys (strings)
 */
function extractCollectionContent(
  def: Def,
  isForOf: boolean,
  node: FlowNode
): Def {
  if (!Def.isObjectDef(def)) {
    return defFactory.createUnknownDef(node);
  }

  if (isForOf) {
    // For-of iterates over values
    return defFactory.createImplicitDef(node, def.values);
  }

  // For-in iterates over property keys
  const keys: Def[] = [];
  for (const key of def.props.keys()) {
    keys.push(defFactory.createLiteralDef(node, key));
  }

  return defFactory.createImplicitDef(node, keys);
}

/**
 * Helper: Handle the left-hand side of for-in / for-of loops.
 *
 * Example:
 *   for (const x of arr)
 *   for (let k in obj)
 *
 * This binds the iterated implicit definition to the declared variable.
 */
function handleForLoopLeft(
  cfgNode: FlowNode,
  left: any,
  collectionDef: Def | null,
  isForOf: boolean
) {
  if (!collectionDef) return;

  const iteratedDef = extractCollectionContent(collectionDef, isForOf, cfgNode);

  // Propagate taint if the iterated collection is tainted
  if (collectionDef.isTainted) {
    taintManager.propagateTaint(
      collectionDef,
      iteratedDef,
      left,
      "ITERATE",
      "loop.iteration"
    );
  }

  // Bind the implicit definition to the left pattern
  if (left.type === "VariableDeclaration") {
    for (const decl of left.declarations) {
      patternAwareTypeHandler(cfgNode, decl.id, iteratedDef);
    }
    return;
  }

  patternAwareTypeHandler(cfgNode, left, iteratedDef);
}
